# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Mohan Rajendran
tagline:             'Personal Website'
description:         'Personal Website'
url:                 mohanrajendran.com
baseurl:             /
excerpt_separator:   <!--excerpt-->
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Mohan Rajendran
  email:             lynermohan@gmail.com

github:
  repo:              https://www.github.com/mohanrajendran

# Collections
collections:
  sicp:
    output: true