# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mohan Rajendran
tagline:          'Blog'
description:      'Hi! I am Mohan Rajendran. A Software Engineer who happens to be an Aerospace Engineer is his previous lifetime. <br> I will be posting snippets from my personal projects and learnings in this blog.'
url:              mohanrajendran.github.io

excerpt_separator: <!--excerpt-->
paginate:         5